# Generated by Django 3.1 on 2020-09-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDp', models.CharField(max_length=100, verbose_name='ID-игрока')),
                ('AchieveBugs', models.BooleanField(default=0)),
                ('AchieveHome', models.BooleanField(default=0)),
                ('AchievePull', models.BooleanField(default=0)),
                ('Achieve5level', models.BooleanField(default=0)),
                ('Achieve20level', models.BooleanField(default=0)),
                ('Achieve35level', models.BooleanField(default=0)),
                ('Achieve50level', models.BooleanField(default=0)),
                ('AchieveNoob', models.BooleanField(default=0)),
                ('AchieveBase', models.BooleanField(default=0)),
                ('AchieveLast', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
    ]
