# Generated by Django 3.1 on 2020-12-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='Code',
            field=models.CharField(max_length=500, null=True, verbose_name='Код_игрока'),
        ),
    ]
