# Generated by Django 3.1 on 2020-12-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_players_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='Code',
            field=models.TextField(max_length=500, null=True, verbose_name='Код_игрока'),
        ),
    ]
